production:
  adapter: postgresql
  database: redmine
  host: localhost
  username: redmine
  password: "my_password"

development:
  adapter: postgresql
  database: redmine_development
  host: localhost
  username: redmine
  password: "my_password"

test:
  adapter: postgresql
  database: redmine_test
  host: localhost
  username: redmine
  password: "my_password"
